name: visidata-ci-build
on:
  pull_request:
    branches:
      - stable
      - develop
  push:
    branches:
    - stable
    - develop
    - workflow_tester

jobs:
  run-tests:

    strategy:
      matrix:
        python-version: ["3.10"]

    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.pythonversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Environment
      run: |
        export PYTHONPATH=~/visidata:~/visidata/visidata
        locale

    - name: Install Base VisiData
      run: pip3 install .

    - name: Ensure VisiData works with Base Dependencies
      run: vd --version

    - name: Ensure VisiData can load a dir
      run: vd . --batch

    - name: Test macros
      run: |
        export TERM=xterm
        mkdir -p ~/.visidata
        cp tests/macros/macros.jsonl tests/macros/1.vdj ~/.visidata/
        vd --overwrite=y -p tests/macros/test_macro.vd
        git --no-pager diff --numstat tests/
        git --no-pager diff --exit-code tests/
